### PR TITLE
Fix compilation error TS2411 on Storage.d.ts

### PR DESCRIPTION
**Pull request by javierdpt**
Got the following errors when updated the package @okta/okta-angular to v3.0.1:

Error: node_modules/@okta/okta-auth-js/lib/types/Storage.d.ts:79:5 - error TS2411: Property 'token' of type 'StorageOptions | undefined' is not
assignable to string index type 'StorageOptions'.

79     token?: StorageOptions;
       ~~~~~

Error: node_modules/@okta/okta-auth-js/lib/types/Storage.d.ts:80:5 - error TS2411: Property 'transaction' of type 'StorageOptions | undefined' is not assignable to string index type 'StorageOptions'.

80     transaction?: StorageOptions;
       ~~~~~~~~~~~

The above fixed it.

### CODE REVIEW

**Review by aarongranick-okta — APPROVED** [review]

**Comment by aarongranick-okta** [comment]
@javierdpt Thanks for catching this! We will get this fix merged in. internal ref: OKTA-369625

**Comment by javierdpt** [comment]
You're very welcome. Thanks for being so responsive.

**Comment by shuowu** [comment]
Merged. Close the PR.
